function(resolve_ebisnis_variant OUT_VAR)
  if(DEFINED EBISNIS_VARIANT AND NOT "${EBISNIS_VARIANT}" STREQUAL "")
    set(${OUT_VAR} "${EBISNIS_VARIANT}" PARENT_SCOPE)
    return()
  endif()

  set(_variant "default")
  set(_generated_config "${CMAKE_CURRENT_SOURCE_DIR}/flutter/ephemeral/generated_config.cmake")
  if(NOT EXISTS "${_generated_config}" AND DEFINED FLUTTER_MANAGED_DIR)
    set(_generated_config "${FLUTTER_MANAGED_DIR}/ephemeral/generated_config.cmake")
  endif()

  if(EXISTS "${_generated_config}")
    file(READ "${_generated_config}" _generated_config_content)
    if(_generated_config_content MATCHES "RUJJU05JU19WQVJJQU5UPWFsYmFoamFo")
      set(_variant "albahjah")
    elseif(_generated_config_content MATCHES "RUJJU05JU19WQVJJQU5UPWludmVudG9yeV9zYWxlcw==")
      set(_variant "inventory_sales")
    elseif(_generated_config_content MATCHES "RUJJU05JU19WQVJJQU5UPWFwb3Rpaw==")
      set(_variant "apotik")
    elseif(_generated_config_content MATCHES "RUJJU05JU19WQVJJQU5UPWRlZmF1bHQ=")
      set(_variant "default")
    elseif(_generated_config_content MATCHES "RUJJU05JU19WQVJJQU5UPWViaXNuaXM=")
      set(_variant "default")
    endif()
  endif()

  set(${OUT_VAR} "${_variant}" PARENT_SCOPE)
endfunction()
