function(resolve_ebisnis_variant OUT_VAR)
  if(DEFINED EBISNIS_VARIANT AND NOT "${EBISNIS_VARIANT}" STREQUAL "")
    set(${OUT_VAR} "${EBISNIS_VARIANT}" PARENT_SCOPE)
    return()
  endif()

  set(_variant "default")
  set(_generated_config "${CMAKE_CURRENT_SOURCE_DIR}/flutter/ephemeral/generated_config.cmake")
  if(NOT EXISTS "${_generated_config}" AND DEFINED FLUTTER_MANAGED_DIR)
    set(_generated_config "${FLUTTER_MANAGED_DIR}/ephemeral/generated_config.cmake")
  endif()

  if(EXISTS "${_generated_config}")
    file(READ "${_generated_config}" _generated_config_content)
    string(REGEX MATCH "DART_DEFINES=([^\"]+)" _dart_defines_match "${_generated_config_content}")
    if(CMAKE_MATCH_1)
      string(REPLACE "," ";" _dart_define_list "${CMAKE_MATCH_1}")
      foreach(_encoded_define ${_dart_define_list})
        string(BASE64_DECODE "${_encoded_define}" _decoded_define)
        if(_decoded_define MATCHES "^EBISNIS_VARIANT=(.*)")
          set(_variant "${CMAKE_MATCH_1}")
        endif()
      endforeach()
    endif()
  endif()

  set(${OUT_VAR} "${_variant}" PARENT_SCOPE)
endfunction()
