class BagianBantuan {
  final String judul;
  final String isi;
  const BagianBantuan(this.judul, this.isi);
}

class ArtikelBantuan {
  final String id;
  final String judul;
  final String ringkasan;
  final List<BagianBantuan> bagian;
  final List<String> workflow;
  final List<String> ilustrasi;
  const ArtikelBantuan({
    required this.id,
    required this.judul,
    required this.ringkasan,
    required this.bagian,
    this.workflow = const [],
    this.ilustrasi = const [],
  });

  int get jumlahKata => bagian
      .map((b) => '${b.judul} ${b.isi}')
      .join(' ')
      .trim()
      .split(RegExp(r'\s+'))
      .where((kata) => kata.isNotEmpty)
      .length;
}

/// Materi dasar yang sengaja dipakai ulang oleh bantuan kontekstual setiap
/// halaman. Dengan satu sumber, perubahan prosedur tidak menghasilkan petunjuk
/// yang saling bertentangan di menu berbeda.
const panduanOperasionalUmum = <BagianBantuan>[
  BagianBantuan(
    'Tujuan, peran pengguna, dan prinsip kerja aman',
    'Halaman POS dipakai untuk mengubah pilihan barang menjadi transaksi penjualan yang tercatat, dapat dibayar, dapat dicetak, dan dapat ditelusuri kembali. Kasir bertugas memastikan barang, jumlah, pelanggan, harga, promo, metode pembayaran, dan uang yang diterima benar sebelum menekan Bayar. Supervisor menangani tindakan yang memerlukan otorisasi seperti pembatalan, pembukaan laci manual, koreksi tertentu, atau penyelesaian selisih. Admin menyiapkan produk, harga, perangkat, cara bayar, toko, dan hak akses. Pemisahan peran ini penting karena tombol yang tidak tampak atau ditolak bukan selalu kerusakan; sering kali akun memang tidak memiliki izin. Jangan meminjam akun orang lain. Gunakan akun sendiri agar audit mencatat pelaku yang benar. Sebelum mulai, periksa nama toko, nama pengguna, status koneksi, printer, laci, dan sesi kas. Jika toko mewajibkan sesi kas, masukkan modal awal sesuai uang nyata di laci. Jangan menebak nominal. Transaksi yang sudah berhasil tidak boleh dibuat ulang hanya karena struk gagal keluar; gunakan cetak ulang dari riwayat. Prinsip utamanya adalah satu kejadian penjualan menghasilkan satu dokumen, satu pembayaran yang dapat direkonsiliasi, dan jejak perubahan yang utuh.',
  ),
  BagianBantuan(
    'Persiapan awal shift dan pemeriksaan sebelum melayani',
    'Mulailah shift dengan memastikan alamat server menunjuk lingkungan yang benar dan indikator sinkronisasi tidak menampilkan kegagalan lama yang belum diselesaikan. Pilih toko atau outlet yang sesuai lokasi fisik. Kesalahan outlet membuat stok, nomor struk, kas, dan laporan masuk ke tempat yang salah. Pastikan tanggal serta jam perangkat benar karena waktu dipakai untuk urutan transaksi, laporan shift, dan sinkronisasi. Buka sesi kas menggunakan jumlah uang tunai yang benar-benar tersedia, bukan saldo perkiraan kemarin. Lakukan uji cetak singkat bila printer baru dinyalakan, kertas diganti, atau koneksi USB/Bluetooth berubah. Periksa laci uang dan layar pelanggan bila digunakan. Pastikan katalog menampilkan produk dan harga terbaru; jalankan sinkronisasi jika ada perubahan master dari kantor. Untuk toko yang beroperasi offline, lihat antrean transaksi tertunda sebelum mulai agar operator mengetahui apakah ada data yang belum sampai ke server. Pisahkan masalah perangkat dari masalah data: printer tidak mencetak tidak berarti penjualan gagal, sedangkan pesan server menolak pembayaran berarti transaksi belum selesai. Catat kondisi awal yang tidak normal kepada supervisor sebelum antrean pelanggan ramai. Pemeriksaan dua menit di awal shift mencegah koreksi panjang di akhir hari.',
  ),
  BagianBantuan(
    'Mencari produk, memindai barcode, dan menyusun keranjang',
    'Fokuskan kolom pencarian lalu pindai barcode. Pemindai biasanya bertindak seperti keyboard dan mengirim Enter; karena itu kursor harus berada di kolom pencarian. Jika barcode tidak ditemukan, cari dengan sebagian nama atau kode produk, pilih kategori, lalu sentuh atau klik kartu produk. Setiap pemilihan menambah barang ke keranjang. Periksa nama, varian, satuan, jumlah, harga satuan, tambahan atau topping, diskon, dan subtotal baris. Produk yang tampak mirip dapat memiliki satuan atau harga berbeda. Gunakan tombol tambah dan kurang untuk mengubah kuantitas; jangan memindai berulang tanpa melihat jumlah. Hapus hanya baris yang memang batal dibeli. Bila produk memiliki pilihan ekstra, selesaikan dialog ekstra sebelum menambahkan agar harga dan deskripsi pesanan akurat. Untuk barang timbang, ikuti konfigurasi barcode timbangan dan pastikan berat terbaca wajar. Peringatan stok adalah alat bantu, bukan alasan mengabaikan barang fisik. Bila stok sistem nol tetapi barang ada, hubungi petugas stok sesuai prosedur, jangan membuat produk pengganti sembarang. Setelah seluruh barang masuk, bandingkan keranjang dengan barang di meja dari kiri ke kanan. Kebiasaan membaca ulang jumlah dan subtotal mengurangi retur akibat salah scan.',
  ),
  BagianBantuan(
    'Memilih pelanggan, promo, pajak, dan harga akhir',
    'Pilih pelanggan atau anggota sebelum pembayaran bila transaksi memakai harga anggota, saldo, limit hutang, poin, cashback, atau riwayat khusus. Cari menggunakan kode, nama, nomor telepon, kartu, atau QR sesuai fasilitas toko. Konfirmasikan identitas tanpa membacakan data pribadi berlebihan. Sesudah pelanggan dipilih, sistem dapat menghitung ulang promo dan harga. Amati subtotal, diskon, cashback, pajak, pembulatan, dan total akhir. Promo otomatis diterapkan jika semua syarat terpenuhi; promo manual harus dipilih oleh kasir. Baca syarat minimal belanja, produk sasaran, periode, kuota, metode pembayaran, dan kemungkinan promo tidak dapat digabung. Jangan menjanjikan diskon sebelum indikator pada keranjang benar-benar berubah. Jika harga di rak berbeda dari aplikasi, hentikan sejenak dan ikuti kebijakan toko: verifikasi label, waktu berlaku, serta produk yang dimaksud. Jangan mengubah harga tanpa hak akses. Untuk transaksi tanpa pelanggan, pastikan pilihan pelanggan sebelumnya sudah dibersihkan agar poin atau hutang tidak masuk ke akun yang salah. Harga akhir yang terlihat sebelum Bayar adalah angka yang harus dikonfirmasi kepada pelanggan. Perubahan pelanggan atau metode pembayaran dapat memicu perhitungan ulang, jadi lakukan pemeriksaan terakhir setelah semua pilihan selesai.',
  ),
  BagianBantuan(
    'Pembayaran tunai, non-tunai, split, dan konfirmasi akhir',
    'Tekan Bayar hanya setelah keranjang dan identitas pelanggan benar. Pilih metode yang benar: tunai, kartu, transfer, QR, saldo anggota, hutang, atau metode lain yang diaktifkan toko. Pada pembayaran tunai, masukkan jumlah yang benar-benar diberikan pelanggan; sistem menghitung kembalian. Hitung uang di depan pelanggan, sebutkan nominal diterima dan kembalian, lalu simpan uang setelah transaksi disetujui agar tidak tertukar. Untuk non-tunai, jangan menganggap tangkapan layar sebagai bukti final. Tunggu status berhasil dari perangkat atau penyedia pembayaran sesuai prosedur. Pada split payment, alokasikan nominal ke setiap metode sampai sisa tepat nol. Periksa bahwa bagian tunai dan non-tunai tidak tertukar. Jangan menekan Bayar berulang saat sistem sedang memproses. Jika respons lambat, lihat indikator dan riwayat sebelum mencoba kembali; kode unik transaksi melindungi dari duplikasi, tetapi disiplin operator tetap diperlukan. Ketika muncul konfirmasi berhasil, catat nomor transaksi dan cetak struk. Jika muncul penolakan, baca pesan lengkap, perbaiki penyebab, kemudian ulangi tindakan yang memang gagal. Jangan membuat keranjang baru sebelum memastikan transaksi pertama tidak tercatat. Untuk transaksi hutang atau saldo, pastikan limit dan otorisasi pelanggan sah.',
  ),
  BagianBantuan(
    'Struk, laci kas, layar pelanggan, dan transaksi tertahan',
    'Setelah pembayaran berhasil, struk dapat dicetak, dibagikan melalui kanal yang disediakan, atau dicetak ulang. Kegagalan printer tidak membatalkan dokumen penjualan. Periksa kertas, tutup printer, kabel, daya, antrean cetak, pilihan printer, dan ukuran kertas; lalu gunakan Cetak Ulang pada transaksi yang sama. Jangan membayar ulang hanya demi memperoleh struk. Laci kas biasanya terbuka saat pembayaran tunai. Pembukaan manual harus memiliki alasan operasional dan dapat dibatasi PIN supervisor. Layar pelanggan menampilkan barang, total, promo, dan status pembayaran; gunakan sebagai sarana konfirmasi, tetapi keranjang kasir tetap sumber pengendalian utama. Keranjang Tertahan berguna saat pelanggan mengambil barang lain atau antrean perlu dilayani bergantian. Beri catatan yang mudah dikenali, simpan, lalu pastikan keranjang aktif kosong sebelum melayani pelanggan berikutnya. Saat melanjutkan keranjang tertahan, periksa ulang harga, promo, stok, pelanggan, dan metode bayar karena kondisi dapat berubah. Hapus keranjang tertahan yang memang tidak dilanjutkan sesuai kewenangan. Jangan memakai fitur tahan sebagai pengganti transaksi kredit. Data tertahan belum merupakan penjualan dan belum boleh dihitung sebagai penerimaan kas.',
  ),
  BagianBantuan(
    'Koneksi terputus, mode offline, dan sinkronisasi',
    'Aplikasi dapat mendukung operasi terbatas saat koneksi tidak stabil. Perhatikan indikator online, jumlah antrean, waktu percobaan terakhir, dan pesan kegagalan. Transaksi offline harus memiliki identitas unik dan disimpan di perangkat sampai server mengakui penerimaan. Jangan menghapus data aplikasi, membersihkan penyimpanan, mengganti perangkat, atau melakukan instal ulang selama antrean masih ada. Tekan Sinkronkan sekali lalu tunggu hasil per item. Status terkirim berarti server telah menerima; status gagal perlu dibaca sebabnya, misalnya sesi berakhir, hak akses berubah, referensi tidak ditemukan, atau data tidak valid. Jangan membuat salinan transaksi untuk mengatasi antrean gagal. Jika internet kembali, sinkronkan sebelum menutup shift. Bandingkan jumlah transaksi lokal, transaksi server, uang tunai, dan metode non-tunai. Bila aplikasi menunjukkan konflik, catat nomor lokal, waktu, nilai, pengguna, dan pesan. Berikan bukti tersebut kepada admin tanpa mengirim sandi. Mode offline bukan izin untuk melewati aturan stok, limit, atau otorisasi. Beberapa metode pembayaran memang harus online. Informasikan kepada pelanggan secara jelas dan pilih alternatif yang sah. Keutuhan data lebih penting daripada memaksa transaksi terlihat selesai pada layar.',
  ),
  BagianBantuan(
    'Retur, pembatalan, koreksi, dan audit',
    'Kesalahan setelah transaksi berhasil ditangani melalui retur atau pembatalan resmi, bukan menghapus dokumen atau membuat penjualan negatif secara manual. Cari transaksi asli melalui nomor struk, tanggal, kasir, atau pelanggan. Cocokkan produk, jumlah, metode bayar, dan alasan. Retur dapat mengembalikan barang ke stok bila kondisi barang memenuhi aturan; barang rusak atau kedaluwarsa dapat memiliki jalur stok berbeda. Pengembalian uang harus mengikuti metode dan persetujuan toko. Pembatalan penuh biasanya memerlukan kewenangan lebih tinggi serta alasan yang dicatat. Dokumen yang sudah posted dipertahankan dan dibuatkan dokumen pembalik agar laporan serta audit tetap dapat dijelaskan. Jangan memakai akun supervisor tanpa kehadirannya. Sebelum menyimpan, baca ringkasan dampak: jumlah dikembalikan, stok, kas, poin, hutang, pajak, dan referensi. Setelah berhasil, cetak atau simpan bukti koreksi dan serahkan kepada pihak terkait. Bila hanya struk salah cetak, gunakan cetak ulang—itu bukan alasan retur. Bila harga salah tetapi transaksi belum dibayar, koreksi keranjang. Bila sudah dibayar, ikuti prosedur resmi. Riwayat audit melindungi kasir dan toko karena menunjukkan apa yang terjadi, kapan, serta oleh siapa.',
  ),
  BagianBantuan(
    'Menutup shift dan melakukan rekonsiliasi',
    'Sebelum menutup sesi, hentikan penerimaan transaksi baru dan selesaikan semua keranjang aktif atau tertahan yang memang harus diproses. Sinkronkan antrean sampai tidak ada transaksi tertunda. Cetak atau buka ringkasan sesi: saldo awal, penjualan tunai, penerimaan non-tunai, pengeluaran atau pembukaan laci yang tercatat, retur, pembatalan, setoran, dan kas seharusnya. Hitung uang fisik menurut pecahan di tempat yang aman. Masukkan kas aktual tanpa menyesuaikan angka agar terlihat sama. Jika ada selisih, hitung ulang, periksa transaksi terakhir, keranjang tertahan, pembayaran split, retur, uang kembalian, dan transaksi yang belum tersinkron. Tulis alasan yang faktual; jangan memakai keterangan umum seperti salah hitung bila penyebab belum diketahui. Supervisor memeriksa dan menyetujui sesuai kebijakan. Cocokkan pula laporan kartu, QR, transfer, saldo, dan hutang dengan sumber masing-masing. Tutup sesi hanya setelah semua bukti tersedia. Logout setelah penutupan agar transaksi shift berikutnya tidak memakai identitas lama. Simpan perangkat, printer, pemindai, dan uang sesuai prosedur. Rekonsiliasi yang konsisten membuat laporan harian dapat dipercaya dan memudahkan penyelesaian selisih tanpa menuduh operator secara keliru.',
  ),
  BagianBantuan(
    'Pemecahan masalah dan informasi yang harus dicatat',
    'Jika halaman tidak merespons, jangan langsung menutup paksa. Tunggu proses aktif, lihat indikator, dan catat tahap terakhir. Untuk masalah produk, catat kode, nama, barcode, toko, harga yang diharapkan, dan harga yang tampil. Untuk pembayaran, catat nomor transaksi, waktu, total, metode, status pada alat pembayaran, serta apakah struk terbentuk. Untuk sinkronisasi, catat ID antrean dan pesan server. Untuk printer, catat nama printer, koneksi, ukuran kertas, dan hasil uji. Ambil tangkapan layar tanpa memperlihatkan sandi, PIN, nomor kartu lengkap, atau data pribadi yang tidak perlu. Coba tindakan aman berurutan: periksa input, tutup dialog, muat ulang data, periksa koneksi, sinkronkan, lalu hubungi supervisor. Hindari menghapus cache, database lokal, atau memasang ulang aplikasi tanpa arahan teknis karena dapat menghilangkan antrean. Pesan akses ditolak diselesaikan melalui pengaturan role, bukan percobaan berulang. Pesan sesi ditutup memerlukan sesi baru atau persetujuan. Pesan duplikat perlu diperiksa di riwayat karena mungkin transaksi pertama sudah diterima. Laporan masalah yang terstruktur mempercepat bantuan: siapa, perangkat apa, outlet mana, kapan, langkah, hasil yang diharapkan, hasil aktual, dan bukti.',
  ),
  BagianBantuan(
    'Cara membaca kartu ringkasan, tabel, filter, dan halaman data',
    'Sebagian besar halaman menggunakan pola yang sama agar mudah dipelajari. Kartu ringkasan di bagian atas menunjukkan keadaan umum, misalnya jumlah transaksi, nilai penjualan, stok menipis, saldo, atau pekerjaan yang belum selesai. Angka pada kartu adalah petunjuk awal, bukan pengganti pemeriksaan rincian. Jika kartu dapat diklik, pilihan tersebut akan membuka atau menyaring data yang membentuk angka itu. Perhatikan judul, periode, toko, status, dan satuan uang sebelum menyimpulkan. Tabel di bawahnya menampilkan rincian dalam halaman-halaman kecil supaya aplikasi tetap ringan. Gunakan tombol halaman berikutnya, sebelumnya, atau nomor halaman; jangan menganggap baris yang terlihat sebagai seluruh data. Tulisan seperti “1–15 dari 240” berarti hanya lima belas baris pertama yang sedang tampil. Kolom pencarian biasanya menerima nama, kode, barcode, nomor telepon, surel, atau nomor dokumen sesuai menu. Masukkan kata yang cukup khusus, tunggu hasil, lalu cocokkan lebih dari satu ciri. Filter tanggal memakai batas awal dan akhir; pastikan zona waktu dan status dokumen sesuai. Tombol Muat Ulang mengambil data terbaru tanpa menghapus input yang telah tersimpan. Tombol Ekspor menghasilkan berkas sesuai filter aktif, sehingga judul laporan dan periode harus diperiksa sebelum dibagikan. Tombol tindakan pada setiap baris hanya berlaku untuk baris tersebut. Buka rincian terlebih dahulu sebelum mengubah, membatalkan, atau mencetak ulang. Warna hijau umumnya menunjukkan selesai atau aktif, kuning membutuhkan perhatian, merah menunjukkan gagal atau berisiko, dan abu-abu menunjukkan tidak aktif. Selalu baca teks status karena warna hanya bantuan visual. Jika tabel kosong, lepaskan filter satu per satu, periksa toko dan tanggal, kemudian muat ulang. Jangan memasukkan data baru hanya karena pencarian pertama belum menemukan hasil; kesalahan ejaan atau filter yang sempit dapat menyebabkan data ganda.',
  ),
  BagianBantuan(
    'Pengelolaan produk, anggota, pemasok, dan data induk',
    'Data induk adalah sumber yang dipakai berulang oleh transaksi dan laporan. Kesalahan pada data induk akan muncul di banyak tempat, sehingga perubahan harus dilakukan dengan teliti. Untuk produk, periksa kode, barcode, nama, kategori, satuan, harga beli, harga jual, pajak, batas stok, status aktif, kebijakan retur, dan toko. Kode dan barcode harus unik sesuai aturan organisasi. Produk baru hanya dibuat setelah pencarian menggunakan gabungan kode, barcode, dan nama tidak menemukan pasangan yang benar. Jangan membuat produk kedua untuk memperbaiki harga atau stok; ubah produk yang sudah ada melalui menu resmi. Untuk anggota, nomor telepon wajib diisi dan harus dinormalisasi, misalnya perbedaan awalan 0 dan +62 tidak boleh menghasilkan dua orang yang sama. Jika nomor sudah terdaftar, gunakan anggota tersebut atau minta admin memperbaiki identitasnya. Cari pula melalui nama, kode, telepon, dan surel. Jangan menyalin nomor milik orang lain untuk melewati validasi. Untuk pemasok, cocokkan nama hukum, kontak, alamat, syarat pembayaran, dan status. Sebelum menyimpan perubahan massal dari Excel, unduh format dari aplikasi, jangan mengubah nama kolom, simpan sebagai XLSX, dan uji beberapa baris lebih dahulu. Layar pratinjau harus menunjukkan data baru serta perbedaan stok, harga beli, dan harga jual. Baris yang sama tidak perlu diproses. Barang baru tetap harus ditampilkan walaupun stok nol. Periksa jumlah baris diterima, dilewati, gagal, dan baru. Setelah komit, ambil sampel hasil di halaman produk dan laporan stok. Perubahan besar sebaiknya dilakukan di luar jam ramai dan didampingi supervisor. Sistem menyimpan jejak pengguna serta waktu, tetapi catatan alasan yang jelas tetap diperlukan agar perubahan dapat dijelaskan pada pemeriksaan berikutnya.',
  ),
  BagianBantuan(
    'Stok, pembelian, mutasi, kedaluwarsa, dan retur barang',
    'Stok bertambah atau berkurang karena dokumen, bukan karena angka pada kartu diedit sembarang. Penerimaan dari pemasok, penjualan, retur, mutasi antaroutlet, stok opname, pemakaian, dan penyesuaian masing-masing mempunyai menu serta bukti sendiri. Saat menerima barang, cocokkan faktur, produk, batch bila ada, tanggal kedaluwarsa, jumlah, satuan, harga, pajak, dan pemasok. Simpan dokumen master beserta seluruh rincian dalam satu proses; bila satu rincian gagal, seluruh dokumen harus dibatalkan agar tidak terjadi data sebagian. Sistem dapat menyimpan salinan JSON sebagai pembanding, tetapi tabel rincian tetap sumber operasional utama. Untuk mutasi, toko asal mengeluarkan barang dan toko tujuan menerima melalui dokumen yang sama. Jangan membuat pengurangan dan penambahan terpisah tanpa referensi. Stok opname membandingkan jumlah fisik dengan sistem pada waktu yang terkendali. Hentikan atau batasi transaksi selama penghitungan sesuai prosedur, masukkan hasil nyata, lalu tinjau selisih sebelum posting. Pengelolaan kedaluwarsa harus memakai prinsip barang yang lebih dahulu berakhir diprioritaskan lebih dahulu, dengan tetap memeriksa kondisi kemasan dan aturan produk. Laporan mendekati kedaluwarsa digunakan untuk pemindahan rak, promosi yang sah, retur pemasok, atau pemusnahan resmi. Jangan menjual barang kedaluwarsa. Retur penjualan hanya boleh mengambil barang dari transaksi asli dan jumlah retur tidak boleh melebihi jumlah dibeli dikurangi retur sebelumnya. Pembelian lima barang dapat diretur dua; sisa tiga tetap tercatat. Kondisi barang menentukan apakah stok kembali tersedia, masuk karantina, atau tidak kembali ke stok jual. Jika sistem menunjukkan stok kosong, hentikan penambahan item, periksa toko aktif dan transaksi yang belum sinkron, lalu lakukan pemeriksaan fisik. Jangan mengubah stok langsung agar penjualan dapat dilanjutkan. Gunakan menu penerimaan, opname, atau penyesuaian dengan alasan dan otorisasi yang benar.',
  ),
  BagianBantuan(
    'Pesanan, pelayanan daring, antrean offline, dan pengiriman ulang',
    'Pesanan dapat berasal dari kasir, pelanggan daring, aplikasi anggota, JSP, Android, atau saluran lain. Setiap pesanan mempunyai kode unik, pemesan, toko, waktu, rincian, total, status pembayaran, dan status pelayanan. Status tertahan berarti keranjang belum menjadi penjualan. Status menunggu bayar berarti pesanan sudah dibuat tetapi penerimaan belum disahkan. Status terbayar berarti pembayaran sudah tercatat. Status terlayani berarti barang atau layanan telah diselesaikan. Jangan mengubah status hanya agar laporan terlihat penuh. Saat memuat pesanan ke kasir, periksa produk, jumlah, harga terbaru, promo, pelanggan, catatan, stok, metode pembayaran, dan toko. Jika rincian berbeda dari bukti pelanggan, hentikan proses dan telusuri sumber; jangan menyimpan versi kedua. Fitur Bayarkan Semua Yang Tertahan harus menampilkan ringkasan jumlah pesanan dan nilai, meminta konfirmasi, memproses secara idempoten, serta melaporkan setiap kegagalan tanpa menyembunyikannya. Ketika jaringan terputus, transaksi final disimpan terlebih dahulu di basis data lokal dengan kode unik, akun, toko, perangkat, dan kode sesi kas asal. Pengirim otomatis mencoba kembali pada interval yang ditentukan, termasuk setiap sepuluh menit, sampai server mengakui transaksi atau menolaknya karena kesalahan bisnis yang harus diperbaiki. Jangan menghapus aplikasi atau basis data saat antrean ada. Satu perangkat tidak boleh mengirim antrean milik akun atau toko lain. Sebelum logout, pindah toko, atau tutup kas, sinkronkan antrean sampai kosong. Jika respons hilang setelah server menyimpan, pengiriman ulang memakai kode yang sama sehingga tidak menciptakan transaksi ganda. Periksa Riwayat Sinkronisasi untuk membedakan belum dikirim, sedang dicoba, berhasil, dan ditolak. Berikan pesan yang mudah dipahami kepada pelanggan, tetapi simpan Informasi Teknis untuk admin. Nomor referensi, waktu, tindakan, perangkat, dan pesan lengkap mempercepat penanganan tanpa meminta pengguna mengulang transaksi secara membabi buta.',
  ),
  BagianBantuan(
    'Sesi kas per pengguna dan perangkat serta rekonsiliasi yang benar',
    'Sesi kas adalah ikatan resmi antara satu akun kasir, satu toko, satu perangkat, dan satu rentang waktu kerja. Contohnya, Udin membuka kas pada mesin 1; hanya transaksi yang dibuat Udin pada mesin 1 dalam sesi tersebut yang masuk ke ringkasan Udin. Susi pada mesin 2 mempunyai sesi dan ringkasan sendiri. Nama kasir saja tidak cukup karena dua orang dapat memiliki nama mirip dan satu akun dapat terbuka di beberapa perangkat. Sistem memakai identitas pengguna, identitas perangkat yang stabil, toko, serta nomor sesi. Saat sesi dibuka, server memberikan izin aktif. Akun yang sama tidak boleh membuka sesi kedua pada perangkat lain sebelum sesi pertama ditutup. Satu perangkat juga tidak boleh dipakai membuka sesi kasir lain selama sesi sebelumnya masih aktif. Jika perangkat asal rusak, supervisor melakukan penutupan resmi berdasarkan bukti, bukan membuat sesi baru diam-diam. Setiap pembayaran menyimpan hubungan langsung ke nomor sesi, disertai salinan perangkat untuk audit. Transaksi lokal yang menunggu jaringan tetap membawa sesi asal dan tidak boleh dipindahkan ke sesi berikutnya. Karena itu Tutup Kas ditolak bila antrean perangkat belum kosong. Ringkasan tunai menjumlahkan pembayaran tunai yang terhubung ke sesi. Non-tunai menjumlahkan kartu, QR, transfer, saldo, dan metode selain tunai sesuai konfigurasi. Kas seharusnya adalah modal awal ditambah penjualan tunai, kemudian disesuaikan oleh transaksi kas resmi seperti retur tunai atau pengeluaran yang memang didukung. Penjualan non-tunai tidak menambah uang fisik di laci. Saat tutup, masukkan uang yang benar-benar dihitung. Sistem menyimpan angka seharusnya, angka fisik, dan selisih. Jangan mengubah uang fisik agar selisih menjadi nol. Riwayat buka dan tutup harus dapat disaring berdasarkan akun, perangkat, toko, dan tanggal agar supervisor dapat melakukan serah terima serta menelusuri perbedaan secara adil.',
  ),
  BagianBantuan(
    'Diskon, promosi grup, harga, dan pengendalian keuntungan',
    'Diskon mengubah nilai yang dibayar dan dapat memengaruhi keuntungan, pajak, komisi, serta laporan. Karena itu aturan harus mempunyai nama, periode mulai dan akhir, status aktif, toko atau saluran yang berlaku, produk sasaran, persentase atau nominal, batas maksimal, syarat minimal, serta pilihan potong langsung atau cashback. Diskon grup memudahkan satu aturan berlaku untuk banyak produk. Daftar produk disimpan sebagai rincian dan salinan JSON pembanding agar perubahan dapat diaudit. Produk dapat ditambahkan satu per satu atau melalui XLSX. Pada unggahan, cocokkan kode, barcode, dan nama; baris yang tidak ditemukan tidak boleh dipasangkan ke produk yang sekadar mirip. Setelah aturan aktif, perhitungan yang sama harus digunakan oleh POS desktop, Android, JSP, ZK, pesanan daring, dan API lain. Server menjadi sumber keputusan akhir agar saluran tidak menghasilkan total berbeda. Pada keranjang, tampilkan harga awal, diskon per baris, diskon transaksi, dan total setelah diskon. Jika tidak ada perubahan, periksa tanggal dan waktu, toko, status aktif, produk, minimal jumlah, metode bayar, pelanggan, kuota, serta apakah aturan dapat digabung. Jangan memberi potongan manual hanya karena pengguna mengharapkan promo; verifikasi syarat dahulu. Jika dua aturan bertumpuk, ikuti prioritas dan kebijakan kombinasi yang telah ditentukan, bukan urutan acak. Perubahan harga beli dan harga jual melalui impor harus ditampilkan sebagai nilai lama, nilai baru, dan selisih. Harga beli tidak boleh terlihat sebagai harga jual. Laporan promo perlu menunjukkan penjualan sebelum diskon, nilai potongan, penjualan setelah diskon, jumlah transaksi, produk, pelanggan atau segmen bila sah, dan margin. Supervisor meninjau promo yang bernilai besar, hampir habis, atau menghasilkan margin negatif. Hentikan aturan yang salah melalui status resmi dan dokumentasikan alasan; jangan menghapus jejak transaksi yang sudah memakai aturan tersebut.',
  ),
  BagianBantuan(
    'Laporan, ekspor XLSX, cetak PDF, grafik, dan penyerahan informasi',
    'Laporan membantu keputusan bila sumber, periode, status, dan satuannya dipahami. Mulailah dengan memilih toko, tanggal awal, tanggal akhir, kategori, pengguna, cara bayar, atau status sesuai kebutuhan. Kartu dan grafik menunjukkan kecenderungan, sedangkan tabel memberikan rincian. Batang yang lebih tinggi tidak selalu berarti keuntungan lebih tinggi; baca judul sumbu, nilai, jumlah transaksi, diskon, retur, dan biaya. Klik kartu atau bagian grafik bila tersedia untuk membuka data pembentuknya. Gunakan paging lima belas baris agar layar ringan; ekspor tetap dapat mengambil seluruh hasil sesuai filter, bukan hanya halaman yang terlihat. Semua file Excel harus berformat XLSX. Buka hasil dan pastikan angka tersimpan sebagai angka, tanggal sebagai tanggal, barcode panjang tidak berubah menjadi notasi ilmiah, judul menyebut periode, dan baris ringkasan sesuai tabel. PDF digunakan untuk hasil yang siap dibaca atau dicetak. Periksa ukuran kertas, orientasi, pemotongan kolom, nomor halaman, identitas toko, dan waktu cetak. Jangan menggunakan tangkapan layar sebagai pengganti laporan resmi bila tombol ekspor tersedia. Laporan Mutasi Barang sebaiknya menunjukkan kategori, kode, barcode, nama, saldo awal, nilai awal, masuk, nilai masuk, keluar, nilai keluar, saldo akhir, dan nilai akhir, berikut jumlah setiap kolom. Buku Pembantu Piutang menunjukkan pelanggan, saldo awal, faktur, pembayaran, retur, uang muka, jurnal umum, dan saldo akhir. Jika angka berbeda, samakan periode dan status, kemudian telusuri dokumen sumber. Simpan laporan pada lokasi yang berizin. Jangan mengirim data anggota, telepon, surel, saldo, atau transaksi ke kanal pribadi. Saat serah terima, jelaskan tujuan laporan, filter yang dipakai, waktu pembuatan, pengecualian, serta tindak lanjut. Dengan demikian penerima tidak salah membaca angka yang benar tetapi konteksnya berbeda.',
  ),
  BagianBantuan(
    'Hak akses, persetujuan supervisor, log kesalahan, dan bantuan teknis',
    'Hak akses menentukan siapa yang boleh melihat, menambah, mengubah, menghapus, membatalkan, mengekspor, atau menyetujui. Pengaturan harus mengikuti tugas nyata dan prinsip kewenangan minimum. Kasir tidak otomatis boleh membatalkan transaksi; supervisor atau pengguna dengan izin hapus dapat melakukannya setelah membaca dampak. Perubahan toko hanya ditawarkan untuk toko yang boleh dilihat oleh grup pengguna. Hak “boleh melihat banyak toko” tidak boleh diganti dengan toko bawaan akun; pilihan terakhir pengguna disimpan secara lokal dan di server, sedangkan toko bawaan dipakai hanya bila belum pernah memilih. Setelah admin mengubah role, pengguna mungkin perlu login kembali atau menyegarkan hak akses. Jika tombol tidak muncul, periksa akun, grup, toko, dan izin tindakan yang tepat. Setiap kegagalan yang nyata harus dicatat ke ErrorLog dengan waktu, pengguna, toko, perangkat, halaman, tindakan, kode referensi, pesan ramah, penyebab teknis, dan jejak exception server. Pengguna melihat judul sederhana, penjelasan apa yang terjadi, dampak, serta langkah aman yang dapat dicoba. Rincian teknis ditempatkan dalam bagian Informasi Teknis yang dapat dibuka dan disalin. Jangan menampilkan sandi, token, nomor kartu lengkap, atau data sensitif di pesan. Di server, exception lengkap tetap dicatat agar pengembang dapat menelusuri penyebab. Tombol Salin Informasi Teknis memudahkan pelaporan tanpa mengetik ulang. Setelah menyalin, pengguna mengirim melalui kanal resmi bersama penjelasan singkat tentang langkah sebelum kendala. Admin menandai status penanganan, menghubungkan kejadian yang sama, dan memantau pola berulang. Kesalahan database, timeout, akses, stok, validasi, printer, dan jaringan perlu dibedakan karena solusinya berbeda. Jangan menjadikan semua peringatan sebagai “server tidak dapat dihubungi”. Pesan yang jujur dan khusus membantu pengguna melakukan langkah mandiri yang aman, sementara log lengkap membantu tim teknis memperbaiki akar masalah.',
  ),
];

/// Versi naratif untuk modul yang memakai layar bantuan khusus (Apotik/eMedik).
String get narasiPanduanOperasionalUmum => panduanOperasionalUmum
    .map((bagian) => '${bagian.judul.toUpperCase()}\n\n${bagian.isi}')
    .join('\n\n');

const artikelBantuan = <ArtikelBantuan>[
  ArtikelBantuan(
    id: 'desktop',
    judul: 'POS Desktop',
    ringkasan:
        'Panduan operator kasir Windows dengan keyboard, scanner, printer, laci, dan layar kedua.',
    bagian: [
      BagianBantuan(
        'Orientasi tampilan desktop dan pintasan utama',
        'Pada desktop, layar dibagi menjadi navigasi, pencarian dan katalog produk, keranjang, ringkasan total, serta tombol tindakan. Ruang lebar memungkinkan katalog dan keranjang terlihat bersamaan. Gunakan mouse untuk eksplorasi dan keyboard untuk pelayanan cepat. F1 membuka bantuan, F2 memulai pembayaran, F3 menahan keranjang, F4 memilih metode bayar, F5 memilih member, F6 membuka laci sesuai izin, F7 memusatkan keranjang, F8 menjalankan sinkronisasi, dan F9 membuka layar pelanggan. Pintasan dapat berbeda menurut konfigurasi; label pada tombol adalah rujukan terakhir. Scanner barcode harus mengarahkan input ke pencarian. Jangan mengetik saat dialog pembayaran terbuka karena karakter dapat masuk ke kolom nominal. Gunakan Tab untuk berpindah kontrol dan Escape untuk menutup dialog yang belum disimpan. Pada monitor ganda, letakkan layar pelanggan di monitor yang menghadap pembeli dan pastikan tidak menampilkan menu admin. Ilustrasi di bawah menunjukkan urutan kerja dari area kiri ke kanan: cari barang, susun keranjang, tinjau total, pilih pembayaran, konfirmasi, lalu cetak. Operator sebaiknya tidak mengubah ukuran jendela selama antrean ramai agar posisi kontrol konsisten dan kesalahan klik berkurang.',
      ),
      ...panduanOperasionalUmum,
    ],
  ),
  ArtikelBantuan(
    id: 'android',
    judul: 'POS Android',
    ringkasan:
        'Panduan kasir ponsel/tablet dengan sentuhan, kamera atau scanner Bluetooth, dan printer mobile.',
    bagian: [
      BagianBantuan(
        'Orientasi Android, sentuhan, dan perangkat bergerak',
        'Pada Android, menu utama dibuka dari ikon navigasi dan panel disusun vertikal agar mudah disentuh. Gulir halaman untuk berpindah dari pencarian ke katalog, keranjang, dan pembayaran. Ketuk sekali, lalu tunggu respons; ketukan berulang dapat menambah kuantitas tanpa sengaja. Gunakan tombol kembali untuk menutup dialog, bukan menutup aplikasi dari daftar recent. Barcode dapat dipindai dengan scanner Bluetooth yang bertindak sebagai keyboard atau fasilitas kamera bila tersedia. Pastikan keyboard virtual tidak menutupi tombol Bayar; tutup keyboard setelah selesai mengetik. Tablet lebih nyaman dalam orientasi lanskap, sedangkan ponsel dapat memakai potret. Jaga baterai di atas batas aman, koneksi Wi-Fi stabil, Bluetooth printer aktif, dan izin aplikasi tidak dicabut. Jangan berbagi hotspot yang tidak dipercaya. Bila layar terkunci di tengah pembayaran, buka kembali aplikasi dan periksa riwayat sebelum mengulang. Diagram menunjukkan alur sentuh yang sama dengan desktop, tetapi setiap tahap tampil sebagai panel berurutan. Ilustrasi perangkat menandai lokasi menu, kolom scan, kartu barang, keranjang, total, dan tombol Bayar. Gunakan stylus hanya bila tidak mengurangi ketepatan sentuhan dan bersihkan layar agar angka tetap mudah dibaca.',
      ),
      ...panduanOperasionalUmum,
    ],
  ),
  ArtikelBantuan(
    id: 'jsp',
    judul: 'POS JSP / Browser',
    ringkasan:
        'Panduan POS web AIS di browser, termasuk sesi, refresh, tab, dan perilaku jaringan.',
    bagian: [
      BagianBantuan(
        'Orientasi browser dan batas aman navigasi',
        'POS JSP berjalan di dalam AIS melalui browser. Pastikan alamat, ikon keamanan jaringan, dan nama lingkungan benar sebelum login. Gunakan satu tab POS aktif per kasir untuk mencegah dua keranjang atau sesi bersaing. Hindari tombol Back, Forward, Refresh, dan penutupan tab ketika pembayaran sedang diproses. Navigasi memakai menu AIS, sedangkan area POS memuat status sesi kas, pencarian barcode, kategori, katalog, keranjang, pembayaran, ringkasan stok, dan transaksi terakhir. F2 memusatkan pencarian dan F12 memulai pembayaran pada implementasi JSP; lihat badge tombol karena pintasan dapat berbeda dari aplikasi Flutter. Browser harus mengizinkan popup untuk layar pelanggan dan pencetakan. Zoom 100 persen direkomendasikan agar tombol dan tabel tidak terpotong. Bila sesi login berakhir, jangan mengisi ulang transaksi sebelum memeriksa apakah pembayaran terakhir sudah tersimpan. Diagram menjelaskan perjalanan data dari browser ke API AIS, validasi hak akses, penyimpanan transaksi, pembaruan stok dan kas, lalu respons untuk struk. Ilustrasi browser menunjukkan bahwa katalog berada di kiri dan keranjang di kanan pada layar lebar, kemudian bertumpuk pada layar sempit. Gunakan reload hanya setelah memastikan tidak ada permintaan aktif dan keranjang penting sudah ditahan.',
      ),
      ...panduanOperasionalUmum,
    ],
  ),
];
